// Generated by CoffeeScript 1.4.0
(function() {

  lychee.define("lychee.ui.Button").requires(["lychee.ui.Sprite", "lychee.ui.Text"]).includes(["lychee.ui.Entity"]).exports(function(lychee, global) {
    return lychee.ui.Button = (function() {

      function Button(data) {
        var settings;
        settings = lychee.extend({}, data);
        this._background = null;
        this._label = null;
        settings.width = 0;
        settings.height = 0;
        if (settings.background != null) {
          this._background = settings.background;
          if (settings.background.width > settings.width) {
            settings.width = settings.background.width;
          }
          if (settings.background.height > settings.height) {
            settings.height = settings.background.height;
          }
        }
        if (settings.label != null) {
          this._label = settings.label;
          if (settings.label.width > settings.width) {
            settings.width = settings.label.width;
          }
          if (settings.label.height > settings.height) {
            settings.height = settings.label.height;
          }
        }
        lychee.ui.Entity.call(this, settings);
        settings = null;
      }

      Button.prototype.getBackground = function() {
        return this._background;
      };

      Button.prototype.getLabel = function() {
        return this._label;
      };

      Button.prototype.update = function(clock, delta) {
        if (this._label !== null) {
          this._label.update(clock, delta);
        }
        if (this._background !== null) {
          return this._background.update(clock, delta);
        }
      };

      return Button;

    })();
  });

}).call(this);
