// Generated by CoffeeScript 1.4.0
(function() {

  lychee.define("lychee.ui.Sprite").includes(["lychee.ui.Entity"]).exports(function(lychee, global) {
    return lychee.ui.Sprite = (function() {

      function Sprite(data) {
        var settings;
        settings = lychee.extend({}, data);
        this._image = null;
        this._map = null;
        if (settings.image !== void 0) {
          this._image = settings.image;
        }
        if (Object.prototype.toString.call(settings.map) === "[object Object]") {
          this._map = settings.map;
        }
        delete settings.image;
        delete settings.map;
        lychee.ui.Entity.call(this, settings);
        settings = null;
      }

      Sprite.prototype.setState = function(id) {
        var h, result, w;
        result = lychee.ui.Entity.prototype.setState.call(this, id);
        if (result === true) {
          w = this._map[this.getState()].width;
          h = this._map[this.getState()].height;
          if (w !== void 0 && typeof w === "number") {
            this.width = w;
          }
          if (h !== void 0 && typeof h === "number") {
            this.height = h;
          }
        }
        return result;
      };

      Sprite.prototype.getImage = function() {
        return this._image;
      };

      Sprite.prototype.getMap = function() {
        var frame, state;
        state = this.getState();
        frame = this.getFrame();
        if ((this._map[state] != null) && (this._map[state].frames != null) && (this._map[state].frames[frame] != null)) {
          return this._map[state].frames[frame];
        }
        return null;
      };

      return Sprite;

    })();
  });

}).call(this);
