// Generated by CoffeeScript 1.4.0
(function() {

  lychee.define("lychee.ui.Text").requires(["lychee.Font"]).includes(["lychee.ui.Entity"]).exports(function(lychee, global) {
    return lychee.ui.Text = (function() {

      function Text(settings) {
        this.font = settings.font || null;
        this.set(settings.text);
        settings.width = this.width;
        settings.height = this.height;
        delete settings.text;
        delete settings.font;
        lychee.ui.Entity.call(this, settings);
      }

      Text.prototype.get = function() {
        return this.text;
      };

      Text.prototype.set = function(text) {
        var chr, fs, height, l, t, width;
        text = (typeof text === "string" ? text : "");
        this.text = text;
        if (this.font instanceof lychee.Font) {
          fs = this.font.getSettings();
          width = 0;
          height = 0;
          t = 0;
          l = this.text.length;
          while (t < l) {
            chr = this.font.get(this.text[t]);
            width += chr.real + fs.kerning;
            height = Math.max(height, chr.height);
            t++;
          }
          this.width = width;
          return this.height = height;
        }
      };

      return Text;

    })();
  });

}).call(this);
