// Generated by CoffeeScript 1.4.0
(function() {

  lychee.define("Input").tags({
    platform: "html"
  }).includes(["lychee.Events"]).supports(function(lychee, global) {
    if (global.document && typeof global.document.addEventListener === "function") {
      return true;
    }
    return false;
  }).exports(function(lychee, global) {
    var Class, Input, _instances, _listeners, _mouseactive;
    _instances = [];
    _mouseactive = false;
    _listeners = {
      keydown: function(event) {
        var i, l, _results;
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          _instances[i]._processKey(event.keyCode, event.ctrlKey, event.altKey, event.shiftKey);
          _results.push(i++);
        }
        return _results;
      },
      touchstart: function(event) {
        var i, l, t, tl, _results;
        event.preventDefault();
        event.stopPropagation();
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          if (event.touches && event.touches.length) {
            t = 0;
            tl = event.touches.length;
            while (t < tl) {
              _instances[i]._processTouch(t, event.touches[t].pageX, event.touches[t].pageY);
              t++;
            }
          } else {
            _instances[i]._processTouch(0, event.pageX, event.pageY);
          }
          _results.push(i++);
        }
        return _results;
      },
      touchmove: function(event) {
        var i, l, t, tl, _results;
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          if (event.touches && event.touches.length) {
            t = 0;
            tl = event.touches.length;
            while (t < tl) {
              _instances[i]._processSwipe(t, "move", event.touches[t].pageX, event.touches[t].pageY);
              t++;
            }
          } else {
            _instances[i]._processSwipe(0, "move", event.pageX, event.pageY);
          }
          _results.push(i++);
        }
        return _results;
      },
      touchend: function(event) {
        var i, l, t, tl, _results;
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          if (event.touches && event.touches.length) {
            t = 0;
            tl = event.touches.length;
            while (t < tl) {
              _instances[i]._processSwipe(t, "end", event.touches[t].pageX, event.touches[t].pageY);
              t++;
            }
          } else {
            _instances[i]._processSwipe(0, "end", event.pageX, event.pageY);
          }
          _results.push(i++);
        }
        return _results;
      },
      mousestart: function(event) {
        var i, l, _results;
        _mouseactive = true;
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          _instances[i]._processTouch(0, event.pageX, event.pageY);
          _results.push(i++);
        }
        return _results;
      },
      mousemove: function(event) {
        var i, l, _results;
        if (_mouseactive === false) {
          return;
        }
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          _instances[i]._processSwipe(0, "move", event.pageX, event.pageY);
          _results.push(i++);
        }
        return _results;
      },
      mouseend: function(event) {
        var i, l, _results;
        if (_mouseactive === false) {
          return;
        }
        _mouseactive = false;
        i = 0;
        l = _instances.length;
        _results = [];
        while (i < l) {
          _instances[i]._processSwipe(0, "end", event.pageX, event.pageY);
          _results.push(i++);
        }
        return _results;
      }
    };
    (function() {
      var keyboard, methods, mouse, touch;
      keyboard = "onkeydown" in global;
      if (keyboard === true) {
        document.addEventListener("keydown", _listeners.keydown, true);
      }
      touch = "ontouchstart" in global;
      mouse = "onmousedown" in global;
      if (touch === true) {
        document.addEventListener("touchstart", _listeners.touchstart, true);
        document.addEventListener("touchmove", _listeners.touchmove, true);
        document.addEventListener("touchend", _listeners.touchend, true);
      } else if (mouse === true) {
        document.addEventListener("mousedown", _listeners.mousestart, true);
        document.addEventListener("mousemove", _listeners.mousemove, true);
        document.addEventListener("mouseup", _listeners.mouseend, true);
        document.addEventListener("mouseout", _listeners.mouseend, true);
      }
      if (lychee.debug === true) {
        methods = [];
        if (keyboard) {
          methods.push("Keyboard");
        }
        if (touch) {
          methods.push("Touch");
        }
        if (mouse) {
          methods.push("Mouse");
        }
        if (methods.length === 0) {
          methods.push("NONE");
        }
        return console.log("lychee.Input: Supported input methods are " + methods.join(", "));
      }
    })();
    return Class = Input = (function() {

      function Input(data) {
        var settings;
        settings = lychee.extend({}, data);
        settings.fireKey = !!settings.fireKey;
        settings.fireModifier = !!settings.fireModifier;
        settings.fireTouch = !!settings.fireTouch;
        settings.fireSwipe = !!settings.fireSwipe;
        settings.delay = (typeof settings.delay === "number" ? settings.delay : 0);
        this._fireKey = settings.fireKey;
        this._fireModifier = settings.fireModifier;
        this._fireTouch = settings.fireTouch;
        this._fireSwipe = settings.fireSwipe;
        this._delay = settings.delay;
        this.reset();
        lychee.Events.call(this, "input");
        _instances.push(this);
        settings = null;
      }

      Input.KEYMAP = {
        8: "backspace",
        9: "tab",
        13: "enter",
        16: "shift",
        17: "ctrl",
        18: "alt",
        19: "pause",
        27: "escape",
        32: "space",
        37: "left",
        38: "up",
        39: "right",
        40: "down",
        48: "0",
        49: "1",
        50: "2",
        51: "3",
        52: "4",
        53: "5",
        54: "6",
        55: "7",
        56: "8",
        57: "9",
        65: "a",
        66: "b",
        67: "c",
        68: "d",
        69: "e",
        70: "f",
        71: "g",
        72: "h",
        73: "i",
        74: "j",
        75: "k",
        76: "l",
        77: "m",
        78: "n",
        79: "o",
        80: "p",
        81: "q",
        82: "r",
        83: "s",
        84: "t",
        85: "u",
        86: "v",
        87: "w",
        88: "x",
        89: "y",
        90: "z"
      };

      Input.prototype.reset = function() {
        this._touchareas = null;
        this._touchareas = {};
        this._swipes = null;
        this._swipes = {
          0: null,
          1: null,
          2: null,
          3: null,
          4: null,
          5: null,
          6: null,
          7: null,
          8: null,
          9: null
        };
        this._clock = null;
        return this._clock = {
          key: Date.now(),
          touch: Date.now(),
          swipe: Date.now()
        };
      };

      Input.prototype.addToucharea = function(id, box) {
        id = (typeof id === "string" ? id : null);
        if (id !== null && Object.prototype.toString.call(box) === "[object Object]" && this._touchareas[id] === void 0) {
          this._touchareas[id] = {
            id: id,
            x1: (typeof box.x1 === "number" ? box.x1 : 0),
            x2: (typeof box.x2 === "number" ? box.x2 : Infinity),
            y1: (typeof box.y1 === "number" ? box.y1 : 0),
            y2: (typeof box.y2 === "number" ? box.y2 : Infinity)
          };
          return true;
        }
        return false;
      };

      Input.prototype.removeToucharea = function(id) {
        id = (typeof id === "string" ? id : null);
        if (id !== null && this._touchareas[id] !== void 0) {
          delete this._touchareas[id];
          return true;
        }
        return false;
      };

      Input.prototype._processKey = function(code, ctrl, alt, shift) {
        var delta, key, name;
        if (this._fireKey === false) {
          return;
        }
        if (Class.KEYMAP[code] === void 0) {
          return;
        }
        ctrl = (ctrl === true ? true : false);
        alt = (alt === true ? true : false);
        shift = (shift === true ? true : false);
        delta = Date.now() - this._clock.key;
        if (delta < this._delay) {
          return;
        }
        if (this._fireModifiers === false && (code === 16 || code === 17 || code === 18) && (ctrl === true || alt === true || shift === true)) {
          return;
        }
        key = Class.KEYMAP[code];
        name = "";
        if (ctrl === true && key !== "ctrl") {
          name += "ctrl-";
        }
        if (alt === true && key !== "alt") {
          name += "alt-";
        }
        if (shift === true && key !== "shift") {
          name += "shift-";
          key = String.fromCharCode(code);
        }
        name += key.toLowerCase();
        if (lychee.debug === true) {
          console.log("lychee.Input:", key, name, delta);
        }
        this.trigger("key", [key, name, delta, event]);
        this.trigger(name, [delta, event]);
        return this._clock.key = Date.now();
      };

      Input.prototype._processTouch = function(id, x, y) {
        var cancelSwipe, delta, tid, toucharea;
        if (this._fireTouch === false) {
          return;
        }
        delta = Date.now() - this._clock.touch;
        if (delta < this._delay) {
          return;
        }
        cancelSwipe = this.trigger("touch", [
          id, {
            x: x,
            y: y
          }, delta
        ]) === true;
        for (tid in this._touchareas) {
          toucharea = this._touchareas[tid];
          if (x > toucharea.x1 && x < toucharea.x2 && y > toucharea.y1 && y < toucharea.y2) {
            this.trigger("toucharea-" + tid, [delta]);
          }
        }
        this._clock.touch = Date.now();
        if (cancelSwipe !== true && this._swipes[id] === null) {
          return this._processSwipe(id, "start", x, y);
        }
      };

      Input.prototype._processSwipe = function(id, state, x, y) {
        var delta, position, swipe;
        if (this._fireSwipe === false) {
          return;
        }
        delta = Date.now() - this._clock.swipe;
        if (delta < this._delay) {
          return;
        }
        position = {
          x: x,
          y: y
        };
        swipe = {
          x: 0,
          y: 0
        };
        if (this._swipes[id] !== null) {
          swipe.x = x - this._swipes[id].x;
          swipe.y = y - this._swipes[id].y;
        }
        if (state === "start") {
          this.trigger("swipe", [id, "start", position, delta, swipe]);
          this._swipes[id] = {
            x: x,
            y: y
          };
        } else if (state === "move") {
          this.trigger("swipe", [id, "move", position, delta, swipe]);
        } else if (state === "end") {
          this.trigger("swipe", [id, "end", position, delta, swipe]);
          this._swipes[id] = null;
        }
        return this._clock.swipe = Date.now();
      };

      return Input;

    })();
  });

}).call(this);
