// Generated by CoffeeScript 1.6.3
(function() {
  lychee.define("lychee.game.State").includes(["lychee.Events"]).exports(function(lychee) {
    var State;
    return State = (function() {
      function State(game, id) {
        this.game = game;
        this.id = id;
        lychee.Events.call(this, "state-" + id);
      }

      State.prototype.enter = function() {
        return this.trigger("enter");
      };

      State.prototype.leave = function() {
        return this.trigger("leave");
      };

      State.prototype.render = function(clock, delta) {};

      State.prototype.update = function(clock, delta) {};

      return State;

    })();
  });

}).call(this);
